name: fade
description: A Widget that animates its visible property with fade and size transitions
version: 1.0.0
authors:
  - Mateusz Wojtczak <mateusz@leancode.pl>
homepage: https://github.com/wojtczakmat/fade

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter